modLoader="javafml"
loaderVersion="[${forge_major},)"
license="MIT"
[[mods]]
modId="netflared"
version="${version}"
displayName="Netflared Server"
description="Cloudflare Tunnel management for Minecraft servers."
authors="matejpcs"
[[dependencies.netflared]]
modId="forge"
mandatory=true
versionRange="[${forge_major},)"
ordering="NONE"
side="SERVER"
[[dependencies.netflared]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="SERVER"
