modLoader="javafml"
loaderVersion="[51,)"
license="MIT"
[[mods]]
modId="netflared"
version="${version}"
displayName="Netflared Server"
description="Cloudflare Tunnel management for Minecraft servers."
authors="matejpcs"
[[dependencies.netflared]]
modId="forge"
mandatory=true
versionRange="[51,)"
ordering="NONE"
side="SERVER"
[[dependencies.netflared]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
